# POSTTEST 6 PENGENALAN TENSORFLOW

Nama : Herni Suhartati <br>
NIM : 2109106001 <br>
Kelas : A1 Informatika 2021 <br>

In [2]:
import tensorflow as tf
from prettytable import PrettyTable

Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [26]:
random_tensor=tf.random.uniform(shape=(5,5), minval=1, maxval=100, dtype=tf.int32 )
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[93, 27, 22, 70, 38],
       [66, 54, 77, 76, 19],
       [44,  1, 11, 57, 50],
       [17, 56, 31, 93, 99],
       [28, 26, 87,  7, 72]])>

Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [27]:
prime_tensor=tf.convert_to_tensor([[2,5,7,11,17],[3,13,19,29,23],[31,41,37,43,47],[2,5,7,41,43],[17,11,7,23,37]])
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 2,  5,  7, 11, 17],
       [ 3, 13, 19, 29, 23],
       [31, 41, 37, 43, 47],
       [ 2,  5,  7, 41, 43],
       [17, 11,  7, 23, 37]])>

Tampilkan dimensi dari kedua variable tersebut.

In [28]:
table=PrettyTable(['Nama', 'Dimensi'])
table.add_row(['random_tensor', random_tensor.shape])
table.add_row(['prime_tensor', prime_tensor.shape])
print(table)

+---------------+---------+
|      Nama     | Dimensi |
+---------------+---------+
| random_tensor |  (5, 5) |
|  prime_tensor |  (5, 5) |
+---------------+---------+


Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

In [29]:
aritmatika=PrettyTable(['Aritmatika', 'Hasil'])
aritmatika.add_row(['Tambah', tf.add(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Kurang', tf.subtract(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Perkalian', tf.multiply(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pembagian', tf.divide(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pangkat', tf.pow(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])

# aritmatika.add_row(['Tambah', tf.math.log(random_tensor,prime_tensor)])
print(aritmatika)



+------------+---------------------------------------------------------------------------------------------+
| Aritmatika |                                            Hasil                                            |
+------------+---------------------------------------------------------------------------------------------+
|   Tambah   |                                          tf.Tensor(                                         |
|            |                                    [[ 95  32  29  81  55]                                   |
|            |                                     [ 69  67  96 105  42]                                   |
|            |                                     [ 75  42  48 100  97]                                   |
|            |                                     [ 19  61  38 134 142]                                   |
|            |                      [ 45  37  94  30 109]], shape=(5, 5), dtype=int32)                     |
|            |     

Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [30]:
import numpy as np


max_row=tf.argmax(random_tensor,axis=0)
min_row=tf.argmin(random_tensor,axis=0)
minim=np.min(random_tensor)
maxim=np.max(random_tensor)
tabel_min_max=PrettyTable(['Nilai', 'Setiap Index', 'Nilai Variabel Random_tensor'])
tabel_min_max.add_row(['Minimum', min_row,minim])
tabel_min_max.add_row(['Maksimum', max_row,maxim])
print(tabel_min_max)




+----------+-------------------------------------------------+------------------------------+
|  Nilai   |                   Setiap Index                  | Nilai Variabel Random_tensor |
+----------+-------------------------------------------------+------------------------------+
| Minimum  | tf.Tensor([3 2 2 4 1], shape=(5,), dtype=int64) |              1               |
| Maksimum | tf.Tensor([0 3 4 3 3], shape=(5,), dtype=int64) |              99              |
+----------+-------------------------------------------------+------------------------------+


Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [32]:
Concat=tf.concat([random_tensor,prime_tensor], axis=1)
Concat

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[93, 27, 22, 70, 38,  2,  5,  7, 11, 17],
       [66, 54, 77, 76, 19,  3, 13, 19, 29, 23],
       [44,  1, 11, 57, 50, 31, 41, 37, 43, 47],
       [17, 56, 31, 93, 99,  2,  5,  7, 41, 43],
       [28, 26, 87,  7, 72, 17, 11,  7, 23, 37]])>

Tampilkan hasil sorting dari kedua variable di atas (descending)

In [33]:
random_desc=tf.sort(random_tensor,direction='DESCENDING')

random_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[93, 70, 38, 27, 22],
       [77, 76, 66, 54, 19],
       [57, 50, 44, 11,  1],
       [99, 93, 56, 31, 17],
       [87, 72, 28, 26,  7]])>

In [34]:
prime_desc=tf.sort(prime_tensor,direction='DESCENDING')
prime_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[17, 11,  7,  5,  2],
       [29, 23, 19, 13,  3],
       [47, 43, 41, 37, 31],
       [43, 41,  7,  5,  2],
       [37, 23, 17, 11,  7]])>