# POSTTEST 6 PENGENALAN TENSORFLOW

Nama : Herni Suhartati <br>
NIM : 2109106001 <br>
Kelas : A1 Informatika 2021 <br>

In [2]:
import tensorflow as tf
from prettytable import PrettyTable

Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [3]:
random_tensor=tf.random.uniform(shape=(5,5), minval=1, maxval=100, dtype=tf.int32 )
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[62, 89, 79,  9, 90],
       [91, 54, 43, 76, 68],
       [27, 59, 64, 78, 73],
       [25, 46, 42, 17, 21],
       [50,  1, 16, 38,  3]])>

Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [4]:
prime_tensor=tf.convert_to_tensor([[2,5,7,11,17],[3,13,19,29,23],[31,41,37,43,47],[2,5,7,41,43],[17,11,7,23,37]])

Tampilkan dimensi dari kedua variable tersebut.

In [5]:
table=PrettyTable(['Nama', 'Dimensi'])
table.add_row(['random_tensor', random_tensor.shape])
table.add_row(['prime_tensor', prime_tensor.shape])
print(table)

+---------------+---------+
|      Nama     | Dimensi |
+---------------+---------+
| random_tensor |  (5, 5) |
|  prime_tensor |  (5, 5) |
+---------------+---------+


Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

In [16]:
aritmatika=PrettyTable(['Aritmatika', 'Hasil'])
aritmatika.add_row(['Tambah', tf.add(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Kurang', tf.subtract(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Perkalian', tf.multiply(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pembagian', tf.divide(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])
aritmatika.add_row(['Pangkat', tf.pow(random_tensor,prime_tensor)])
aritmatika.add_row(['',''])

# aritmatika.add_row(['Tambah', tf.math.log(random_tensor,prime_tensor)])
print(aritmatika)



[[64 94 86 20 107]
 [94 67 62 105 91]
 [58 100 101 121 120]
 [27 51 49 58 64]
 [67 12 23 61 40]]
+------------+-----------------------------------------------------------------------------------------------+
| Aritmatika |                                             Hasil                                             |
+------------+-----------------------------------------------------------------------------------------------+
|   Tambah   |                                              None                                             |
|            |                                                                                               |
|   Kurang   |                                           tf.Tensor(                                          |
|            |                                     [[ 60  84  72  -2  73]                                    |
|            |                                      [ 88  41  24  47  45]                                    |
|            | 

Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [13]:
max_row=tf.argmax(random_tensor,axis=0)
tf.print(max_row)


[1 0 0 2 0]


In [25]:
from random import random


min_row=tf.argmin(random_tensor,axis=0)
min_row

tf.minimum(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 2,  5,  7,  9, 17],
       [ 3, 13, 19, 29, 23],
       [27, 41, 37, 43, 47],
       [ 2,  5,  7, 17, 21],
       [17,  1,  7, 23,  3]])>

Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [20]:
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[62, 89, 79,  9, 90],
       [91, 54, 43, 76, 68],
       [27, 59, 64, 78, 73],
       [25, 46, 42, 17, 21],
       [50,  1, 16, 38,  3]])>

In [9]:
Concat=tf.concat([random_tensor,prime_tensor], axis=1)
Concat

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[62, 89, 79,  9, 90,  2,  5,  7, 11, 17],
       [91, 54, 43, 76, 68,  3, 13, 19, 29, 23],
       [27, 59, 64, 78, 73, 31, 41, 37, 43, 47],
       [25, 46, 42, 17, 21,  2,  5,  7, 41, 43],
       [50,  1, 16, 38,  3, 17, 11,  7, 23, 37]])>

Tampilkan hasil sorting dari kedua variable di atas (descending)

In [10]:
random_desc=tf.sort(random_tensor,direction='DESCENDING')

random_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[90, 89, 79, 62,  9],
       [91, 76, 68, 54, 43],
       [78, 73, 64, 59, 27],
       [46, 42, 25, 21, 17],
       [50, 38, 16,  3,  1]])>

In [11]:
prime_desc=tf.sort(prime_tensor,direction='DESCENDING')
prime_desc

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[17, 11,  7,  5,  2],
       [29, 23, 19, 13,  3],
       [47, 43, 41, 37, 31],
       [43, 41,  7,  5,  2],
       [37, 23, 17, 11,  7]])>